# Pandemic Policies

The data is sourced from Oxford University's Covid-19 Government Response Tracker. The data link is the GitHub repository which is updated on a daily basis. The program filters the obtained data for US states, and focuses on mainly four indices - Stringency Index, Government Response Index, Containment Health Index, and Economic Index. The methodology for calculating the indices can be found here: https://github.com/OxCGRT/covid-policy-tracker/blob/master/documentation/index_methodology.md. The dataset is grouped for each state and corresponding year/month.

In [1]:
# Import libraries
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import warnings
import os
import sys
sys.path.append("../")

In [2]:
# Read the dataset in csv format
data = pd.read_csv('https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/OxCGRT_latest.csv')

C:\Users\himan\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (2,3) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
data.head()

,CountryName,CountryCode,RegionName,RegionCode,Jurisdiction,Date,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
0,Aruba,ABW,NaN,NaN,NAT_TOTAL,20200101,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Aruba,ABW,NaN,NaN,NAT_TOTAL,20200102,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Aruba,ABW,NaN,NaN,NAT_TOTAL,20200103,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Aruba,ABW,NaN,NaN,NAT_TOTAL,20200104,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Aruba,ABW,NaN,NaN,NAT_TOTAL,20200105,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
# Extract data for US states
state_data = data[(data['CountryName'] == 'United States') & (data['Jurisdiction'] =='STATE_TOTAL')]
state_data

,CountryName,CountryCode,RegionName,RegionCode,Jurisdiction,Date,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
145404,United States,USA,Alaska,US_AK,STATE_TOTAL,20200101,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
145405,United States,USA,Alaska,US_AK,STATE_TOTAL,20200102,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
145406,United States,USA,Alaska,US_AK,STATE_TOTAL,20200103,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
145407,United States,USA,Alaska,US_AK,STATE_TOTAL,20200104,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
145408,United States,USA,Alaska,US_AK,STATE_TOTAL,20200105,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174826,United States,USA,Wyoming,US_WY,STATE_TOTAL,20210726,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174827,United States,USA,Wyoming,US_WY,STATE_TOTAL,20210727,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174828,United States,USA,Wyoming,US_WY,STATE_TOTAL,20210728,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174829,United States,USA,Wyoming,US_WY,STATE_TOTAL,20210729,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174830,United States,USA,Wyoming,US_WY,STATE_TOTAL,20210730,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Number of states
len(state_data['RegionName'].unique())

51

In [6]:
# Fill the NaNs with 0
state_data[['GovernmentResponseIndex','StringencyIndex','ContainmentHealthIndex','EconomicSupportIndex']]

,GovernmentResponseIndex,StringencyIndex,ContainmentHealthIndex,EconomicSupportIndex
145404,0.0,0.0,0.0,0.0
145405,0.0,0.0,0.0,0.0
145406,0.0,0.0,0.0,0.0
145407,0.0,0.0,0.0,0.0
145408,0.0,0.0,0.0,0.0
...,...,...,...,...
174826,NaN,NaN,NaN,NaN
174827,NaN,NaN,NaN,NaN
174828,NaN,NaN,NaN,NaN
174829,NaN,NaN,NaN,NaN
174830,NaN,NaN,NaN,NaN

In [7]:
# Change the index of the dataframe to date
state_data.index = pd.to_datetime(state_data['Date'],format='%Y%m%d')
# Group the data based on state name, month, and year
state_grouped = state_data.groupby(by=[state_data.RegionName.rename('state'), state_data.index.year.rename('year'), state_data.index.month.rename('month')]).mean().reset_index()
state_grouped

,state,year,month,Date,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,C3_Cancel public events,C3_Flag,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
0,Alabama,2020,1,20200116.0,0.000000,NaN,0.000000,NaN,0.000000,NaN,...,0.000000,0.000000,0.000000,0.000000,1.949355,1.949355,2.111290,2.111290,0.806452,0.806452
1,Alabama,2020,2,20200215.0,0.000000,NaN,0.000000,NaN,0.000000,NaN,...,0.000000,0.000000,0.000000,0.000000,5.210000,5.210000,5.950000,5.950000,0.000000,0.000000
2,Alabama,2020,3,20200316.0,1.419355,1.000000,1.516129,0.450000,1.096774,0.263158,...,38.574194,38.574194,43.524194,43.524194,33.896129,33.896129,36.664839,36.664839,14.516129,14.516129
3,Alabama,2020,4,20200415.5,3.000000,0.966667,2.966667,1.000000,2.000000,1.000000,...,78.873667,78.873667,82.616000,82.616000,70.249333,70.249333,71.355667,71.355667,62.500000,62.500000
4,Alabama,2020,5,20200516.0,3.000000,0.000000,2.000000,0.677419,2.000000,0.677419,...,66.784194,66.784194,72.312903,72.312903,65.953548,65.953548,66.445161,66.445161,62.500000,62.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
964,Wyoming,2021,3,20210316.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,56.900323,56.900323,68.779355,68.779355,56.421613,56.421613,57.454516,57.454516,49.193548,49.193548
965,Wyoming,2021,4,20210415.5,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,51.973667,51.973667,67.860000,67.860000,53.348667,53.348667,55.608333,55.608333,37.500000,37.500000
966,Wyoming,2021,5,20210516.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,49.880645,49.880645,67.860000,67.860000,53.428387,53.428387,55.700968,55.700968,37.500000,37.500000
967,Wyoming,2021,6,20210615.5,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,46.300000,46.300000,67.860000,67.860000,51.560000,51.560000,53.570000,53.570000,37.500000,37.500000
968,Wyoming,2021,7,20210715.5,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,46.300000,46.300000,67.860000,67.860000,51.888421,51.888421,53.476316,53.476316,41.250000,41.250000

In [8]:
# Drop irrelevant columns
state_grouped.drop(state_grouped.columns.difference(['state','month','year','GovernmentResponseIndex','StringencyIndex','ContainmentHealthIndex','EconomicSupportIndex']), 1, inplace=True)

In [9]:
state_grouped = state_grouped.fillna(0)
state_grouped

,state,year,month,StringencyIndex,GovernmentResponseIndex,ContainmentHealthIndex,EconomicSupportIndex
0,Alabama,2020,1,0.000000,1.949355,2.111290,0.806452
1,Alabama,2020,2,0.000000,5.210000,5.950000,0.000000
2,Alabama,2020,3,38.574194,33.896129,36.664839,14.516129
3,Alabama,2020,4,78.873667,70.249333,71.355667,62.500000
4,Alabama,2020,5,66.784194,65.953548,66.445161,62.500000
...,...,...,...,...,...,...,...
964,Wyoming,2021,3,56.900323,56.421613,57.454516,49.193548
965,Wyoming,2021,4,51.973667,53.348667,55.608333,37.500000
966,Wyoming,2021,5,49.880645,53.428387,55.700968,37.500000
967,Wyoming,2021,6,46.300000,51.560000,53.570000,37.500000
968,Wyoming,2021,7,46.300000,51.888421,53.476316,41.250000

In [10]:
# Go to the Input folder
get_path = sys.path[0].split("\\")      # Get the path of current folder
del get_path[-1]                        # Delete the folder name to get path of the parent directory
cwd = "input"                           # Name the directory you need to access files from
get_path.append(cwd)                    # Append it to the list with the parent directory
path = "\\".join(get_path)              # Join the list items to a string
os.chdir(path)                          # Load the directory as the child directory

In [11]:
state_codes = pd.read_csv("State_msa_names.csv")
state_codes.head(5)

  state_abbr  fips_state      state_name    state_proper
0         AK           2          ALASKA          Alaska
1         AL           1         ALABAMA         Alabama
2         AR           5        ARKANSAS        Arkansas
3         AS          60  AMERICAN SAMOA  American Samoa
4         AZ           4         ARIZONA         Arizona

In [12]:
# Merge state codes
merged = pd.merge(state_grouped, state_codes, left_on='state', right_on='state_proper')
merged

,state,year,month,StringencyIndex,GovernmentResponseIndex,ContainmentHealthIndex,EconomicSupportIndex,state_abbr,fips_state,state_name,state_proper
0,Alabama,2020,1,0.000000,1.949355,2.111290,0.806452,AL,1,ALABAMA,Alabama
1,Alabama,2020,2,0.000000,5.210000,5.950000,0.000000,AL,1,ALABAMA,Alabama
2,Alabama,2020,3,38.574194,33.896129,36.664839,14.516129,AL,1,ALABAMA,Alabama
3,Alabama,2020,4,78.873667,70.249333,71.355667,62.500000,AL,1,ALABAMA,Alabama
4,Alabama,2020,5,66.784194,65.953548,66.445161,62.500000,AL,1,ALABAMA,Alabama
...,...,...,...,...,...,...,...,...,...,...,...
945,Wyoming,2021,3,56.900323,56.421613,57.454516,49.193548,WY,56,WYOMING,Wyoming
946,Wyoming,2021,4,51.973667,53.348667,55.608333,37.500000,WY,56,WYOMING,Wyoming
947,Wyoming,2021,5,49.880645,53.428387,55.700968,37.500000,WY,56,WYOMING,Wyoming
948,Wyoming,2021,6,46.300000,51.560000,53.570000,37.500000,WY,56,WYOMING,Wyoming
949,Wyoming,2021,7,46.300000,51.888421,53.476316,41.250000,WY,56,WYOMING,Wyoming

In [13]:
# Go to the Output folder
get_path = sys.path[0].split("\\")
del get_path[-1]
cwd = "output"
get_path.append(cwd)
path = "\\".join(get_path)
os.chdir(path)

In [14]:
# Convert the output to csv
merged.to_csv('pandemic_policies.csv')