# Pandemic Policies

The data is sourced from Oxford University's Covid-19 Government Response Tracker. The data link is the GitHub repository which is updated on a daily basis. The program filters the obtained data for US states, and focuses on mainly four indices - Stringency Index, Government Response Index, Containment Health Index, and Economic Index. The dataset is grouped for each state and corresponding month/year.

In [134]:
# Import libraries
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import warnings
import os
import sys
sys.path.append("../")

In [135]:
# Read the dataset in csv format
data = pd.read_csv('https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/OxCGRT_latest.csv')

C:\Users\himan\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (2,3) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [136]:
data.head()

,CountryName,CountryCode,RegionName,RegionCode,Jurisdiction,Date,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
0,Aruba,ABW,NaN,NaN,NAT_TOTAL,20200101,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Aruba,ABW,NaN,NaN,NAT_TOTAL,20200102,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Aruba,ABW,NaN,NaN,NAT_TOTAL,20200103,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Aruba,ABW,NaN,NaN,NAT_TOTAL,20200104,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Aruba,ABW,NaN,NaN,NAT_TOTAL,20200105,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [137]:
# Extract data for US states
state_data = data[(data['CountryName'] == 'United States') & (data['Jurisdiction'] =='STATE_TOTAL')]
state_data = state_data.fillna(0)
state_data

,CountryName,CountryCode,RegionName,RegionCode,Jurisdiction,Date,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
141372,United States,USA,Alaska,US_AK,STATE_TOTAL,20200101,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
141373,United States,USA,Alaska,US_AK,STATE_TOTAL,20200102,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
141374,United States,USA,Alaska,US_AK,STATE_TOTAL,20200103,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
141375,United States,USA,Alaska,US_AK,STATE_TOTAL,20200104,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
141376,United States,USA,Alaska,US_AK,STATE_TOTAL,20200105,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169978,United States,USA,Wyoming,US_WY,STATE_TOTAL,20210710,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
169979,United States,USA,Wyoming,US_WY,STATE_TOTAL,20210711,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
169980,United States,USA,Wyoming,US_WY,STATE_TOTAL,20210712,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
169981,United States,USA,Wyoming,US_WY,STATE_TOTAL,20210713,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
169982,United States,USA,Wyoming,US_WY,STATE_TOTAL,20210714,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [138]:
# Number of states
len(state_data['RegionName'].unique())

51

In [139]:
# Fill the NaNs with 0
state_data[['GovernmentResponseIndex','StringencyIndex','ContainmentHealthIndex','EconomicSupportIndex']]

,GovernmentResponseIndex,StringencyIndex,ContainmentHealthIndex,EconomicSupportIndex
141372,0.0,0.0,0.0,0.0
141373,0.0,0.0,0.0,0.0
141374,0.0,0.0,0.0,0.0
141375,0.0,0.0,0.0,0.0
141376,0.0,0.0,0.0,0.0
...,...,...,...,...
169978,0.0,0.0,0.0,0.0
169979,0.0,0.0,0.0,0.0
169980,0.0,0.0,0.0,0.0
169981,0.0,0.0,0.0,0.0
169982,0.0,0.0,0.0,0.0

In [140]:
# Change the index of the dataframe to date
state_data.index = pd.to_datetime(state_data['Date'],format='%Y%m%d')
# Group the data based on state name, month, and year
state_grouped = state_data.groupby(by=[state_data.RegionName.rename('state'), state_data.index.month.rename('month'), state_data.index.year.rename('year')]).mean().reset_index()
state_grouped

,state,month,year,Date,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,C3_Cancel public events,C3_Flag,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
0,Alabama,1,2020,20200116.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,1.949355,1.949355,2.111290,2.111290,0.806452,0.806452
1,Alabama,1,2021,20210116.0,2.000000,0.000000,1.000000,1.000000,1.000000,1.00000,...,44.775484,44.775484,60.484194,60.484194,49.242903,49.242903,50.918387,50.918387,37.500000,37.500000
2,Alabama,2,2020,20200215.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,5.210000,5.210000,5.950000,5.950000,0.000000,0.000000
3,Alabama,2,2021,20210214.5,2.000000,0.000000,1.000000,1.000000,1.000000,1.00000,...,46.300000,46.300000,63.100000,63.100000,49.380000,49.380000,51.070000,51.070000,37.500000,37.500000
4,Alabama,3,2020,20200316.0,1.419355,0.612903,1.516129,0.290323,1.096774,0.16129,...,38.574194,38.574194,43.524194,43.524194,33.896129,33.896129,36.664839,36.664839,14.516129,14.516129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
964,Wyoming,8,2020,20200816.0,2.741935,0.000000,1.000000,1.000000,1.000000,1.00000,...,60.155161,60.155161,70.508710,70.508710,59.360645,59.360645,58.905806,58.905806,62.500000,62.500000
965,Wyoming,9,2020,20200915.5,1.900000,0.100000,1.000000,1.000000,1.000000,1.00000,...,57.225000,57.225000,67.860000,67.860000,53.851333,53.851333,57.021000,57.021000,31.666667,31.666667
966,Wyoming,10,2020,20201016.0,1.129032,0.870968,1.000000,1.000000,1.000000,1.00000,...,55.798710,55.798710,67.860000,67.860000,51.341935,51.341935,55.105484,55.105484,25.000000,25.000000
967,Wyoming,11,2020,20201115.5,2.000000,0.000000,1.000000,1.000000,1.000000,1.00000,...,58.522000,58.522000,68.620000,68.620000,53.748000,53.748000,57.856000,57.856000,25.000000,25.000000
968,Wyoming,12,2020,20201216.0,1.935484,0.064516,1.000000,1.000000,1.677419,1.00000,...,65.892258,65.892258,71.881935,71.881935,59.164194,59.164194,63.470645,63.470645,29.032258,29.032258

In [142]:
# Drop irrelevant columns
state_grouped.drop(state_grouped.columns.difference(['state','month','year','GovernmentResponseIndex','StringencyIndex','ContainmentHealthIndex','EconomicSupportIndex']), 1, inplace=True)

In [143]:
state_grouped

,state,month,year,StringencyIndex,GovernmentResponseIndex,ContainmentHealthIndex,EconomicSupportIndex
0,Alabama,1,2020,0.000000,1.949355,2.111290,0.806452
1,Alabama,1,2021,44.775484,49.242903,50.918387,37.500000
2,Alabama,2,2020,0.000000,5.210000,5.950000,0.000000
3,Alabama,2,2021,46.300000,49.380000,51.070000,37.500000
4,Alabama,3,2020,38.574194,33.896129,36.664839,14.516129
...,...,...,...,...,...,...,...
964,Wyoming,8,2020,60.155161,59.360645,58.905806,62.500000
965,Wyoming,9,2020,57.225000,53.851333,57.021000,31.666667
966,Wyoming,10,2020,55.798710,51.341935,55.105484,25.000000
967,Wyoming,11,2020,58.522000,53.748000,57.856000,25.000000
968,Wyoming,12,2020,65.892258,59.164194,63.470645,29.032258

In [144]:
# Go to the Input folder
get_path = sys.path[0].split("\\")
del get_path[-1]
cwd = "input"
get_path.append(cwd)
path = "\\".join(get_path)
os.chdir(path)

In [145]:
state_codes = pd.read_csv("State_msa_names.csv")
state_codes.head(5)

  state_abbr  fips_state      state_name    state_proper
0         AK           2          ALASKA          Alaska
1         AL           1         ALABAMA         Alabama
2         AR           5        ARKANSAS        Arkansas
3         AS          60  AMERICAN SAMOA  American Samoa
4         AZ           4         ARIZONA         Arizona

In [146]:
# Merge state codes
merged = pd.merge(state_grouped, state_codes, left_on='state', right_on='state_proper')
merged

,state,month,year,StringencyIndex,GovernmentResponseIndex,ContainmentHealthIndex,EconomicSupportIndex,state_abbr,fips_state,state_name,state_proper
0,Alabama,1,2020,0.000000,1.949355,2.111290,0.806452,AL,1,ALABAMA,Alabama
1,Alabama,1,2021,44.775484,49.242903,50.918387,37.500000,AL,1,ALABAMA,Alabama
2,Alabama,2,2020,0.000000,5.210000,5.950000,0.000000,AL,1,ALABAMA,Alabama
3,Alabama,2,2021,46.300000,49.380000,51.070000,37.500000,AL,1,ALABAMA,Alabama
4,Alabama,3,2020,38.574194,33.896129,36.664839,14.516129,AL,1,ALABAMA,Alabama
...,...,...,...,...,...,...,...,...,...,...,...
945,Wyoming,8,2020,60.155161,59.360645,58.905806,62.500000,WY,56,WYOMING,Wyoming
946,Wyoming,9,2020,57.225000,53.851333,57.021000,31.666667,WY,56,WYOMING,Wyoming
947,Wyoming,10,2020,55.798710,51.341935,55.105484,25.000000,WY,56,WYOMING,Wyoming
948,Wyoming,11,2020,58.522000,53.748000,57.856000,25.000000,WY,56,WYOMING,Wyoming
949,Wyoming,12,2020,65.892258,59.164194,63.470645,29.032258,WY,56,WYOMING,Wyoming

In [147]:
# Go to the Output folder
get_path = sys.path[0].split("\\")
del get_path[-1]
cwd = "output"
get_path.append(cwd)
path = "\\".join(get_path)
os.chdir(path)

In [148]:
# Convert the output to csv
merged.to_csv('pandemic_policies.csv')